FROM centos/python-36-centos7:latest

USER root

COPY . /tmp/src

RUN rm -rf /tmp/src/.git* && \
    chown -R 1001 /tmp/src && \
    chgrp -R 0 /tmp/src && \
    chmod -R g+w /tmp/src && \
    rm -rf /tmp/scripts && \
    mv /tmp/src/.s2i/bin /tmp/scripts

USER 1001

LABEL io.k8s.description="S2I builder for custom Jupyter notebooks." \
      io.k8s.display-name="Jupyter Notebook" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="builder,jupyter" \
      io.openshift.s2i.scripts-url="image:///opt/app-root/builder"

# Added by Ajay
RUN cd /tmp/ && curl -O https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.7/openshift-client-linux-4.7.60.tar.gz && \
    tar -xvf /tmp/openshift-client-linux-4.7.60.tar.gz
RUN cp /tmp/oc /opt/app-root/bin/oc && chmod +x /opt/app-root/bin/oc 

chmod +x /opt/app-root/bin/oc

RUN /tmp/scripts/assemble

CMD [ "/opt/app-root/builder/run" ]
